config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :carts, only: [:index] do
    collection do
      post '/add/:product_id', to: 'carts#add', as: :add
      delete '/remove/:cart_item_id', to: 'carts#remove', as: :remove
    end
  end

  get '/checkout', to: 'checkout#index', as: 'checkout'
  post '/checkout', to: 'checkout#create', as: 'create_checkout'
  get '/payment', to: 'checkout#payment', as: 'payment'
  post '/pay', to: 'checkout#pay', as: 'pay'
  get '/confirm', to: 'checkout#confirm', as: 'confirm'

  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def moltin
    @moltin ||= Moltin::Client.new({
      storage: session,
      logger: Rails.logger
    })
  end

  def cart
    @cart ||= moltin.carts.get(cart_ref)
  end

  def cart_ref
    session[:cart_id] ||= SecureRandom.hex
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @items = cart.items
  end

  def add
    cart.add(id: params[:product_id])
    redirect_to carts_path
  end

  def remove
    cart.remove(params[:cart_item_id])
    redirect_to carts_path
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
  end

  def create
    customer = {
      name: "#{params[:first_name]} #{params[:last_name]}",
      email: params[:email]
    }
    order = cart.checkout(customer: customer,
                          billing_address: fake_address,
                          shipping_address: fake_address).data
    session[:order_id] = order.id
    session[:first_name] = params[:first_name]
    session[:last_name] = params[:last_name]
    redirect_to payment_path
  end

  def payment
  end

  def pay
    payment = moltin.orders.get(session[:order_id]).pay({
      gateway: 'stripe',
      method: 'purchase',
      first_name: session[:first_name],
      last_name: session[:last_name],
      number: params[:card_number],
      month: params[:card_expiry].split('/')[0],
      year: params[:card_expiry].split('/')[1],
      verification_value: params[:card_cvc]
    })

    redirect_to confirm_path
  end

  def confirm
    session.delete(:cart_id)
    session.delete(:order_id)
    session.delete(:first_name)
    session.delete(:last_name)
  end

  private

  # Using a fake address since we send digital products
  # and don't want to bother the user with that. An email is enough
  # to deliver the products.
  def fake_address
    {
      first_name: 'Jack',
      last_name: 'Macdowall',
      company_name: 'Macdowalls',
      line_1: '1225 Invention Avenue',
      line_2: 'Birmingham',
      postcode: 'B21 9AF',
      county: 'West Midlands',
      country: 'UK'
    }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    offset = params[:page] ? (params[:page].to_i - 1) * 12 : 0
    @products = moltin.products.all.
                                limit(12).
                                offset(offset).
                                sort('name').
                                with(:files).
                                filter(eq: { status: 'live' })

    @query = params[:query]
    @products = @products.filter(like: { name: "'*#{@query}*'" }) if @query.present?
    @page = @products.response_meta['page']
  end

  def show
    @product = moltin.products.get(params[:id]).with(:files)
    @images = (@product.files || []).drop(1).map { |f| @product.included.find('files', f.id) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/money_helper.rb
module MoneyHelper
  def money(hash)
    Money.new(hash['amount'], hash['currency']).format
  end
end

app/views/carts/index.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <div class='well'>
      <h1>Cart</h1>
      <% if @items.any? %>
        <table class="table">
          <%- @items.each do |item| %>
            <tr>
              <th>Item</th>
              <th>Price</th>
              <th>Qty</th>
              <th>Total</th>
            </tr>
            <tr>
              <td><%= item.name %> - <%= link_to 'Remove', remove_carts_path(cart_item_id: item.id), method: :delete %></td>
              <td><%= money(item.unit_price) %></td>
              <td><%= item.quantity %></td>
              <td><%= money(item.value) %></td>
            </tr>
          <% end %>
          <tr>
            <td>Total before taxes:</td>
            <td></td>
            <td></td>
            <td><%= money(@cart.meta['display_price']['without_tax']) %></td>
          </tr>
          <tr>
            <td>Total including taxes:</td>
            <td></td>
            <td></td>
            <td><%= money(@cart.meta['display_price']['with_tax']) %></td>
          </tr>
        </table>
        <%= link_to 'Checkout', checkout_path, class: 'btn btn-primary pull-right' %>
        <div class='clearfix'></div>
      <% else %>
        Your cart is empty.
      <% end %>
    </div>
  </div>
</div>

app/views/checkout/confirm.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-6 col-md-offset-3'>
    <div class='well'>
      <h1>Purchase Successful</h1>
      <p>Thank you for your purchase. It will be delivered to your email address shortly.</p>
    </div>
</div>

app/views/checkout/index.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-6 col-md-offset-3'>
    <div class='well'>
      <h1>Checkout</h1>
      <%= form_tag create_checkout_path do %>
        <div class='row'>
          <div class='col-xs-12'>
            <div class="form-group">
              <label for="email">Email</label>
              <%= email_field_tag :email, '', class: 'form-control', placeholder: 'Email...' %>
            </div>

            <div class='row'>
              <div class='col-xs-12 col-md-6'>
                <div class="form-group">
                  <label for="first_name">First Name</label>
                  <%= text_field_tag :first_name, '', class: 'form-control', placeholder: 'First Name...' %>
                </div>
              </div>
              <div class='col-xs-12 col-md-6'>
                <div class="form-group">
                  <label for="last_name">Last Name</label>
                  <%= text_field_tag :last_name, '', class: 'form-control', placeholder: 'Last Name...' %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class='row'>
          <div class="col-xs-12">
              <button class="subscribe btn btn-success btn-lg btn-block" type="submit">
                Checkout
              </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/checkout/payment.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-6 col-md-offset-3'>
    <div class='well'>
      <h1>Payment</h1>
      <%= form_tag pay_path do %>
        <div class='row'>
          <div class='col-xs-12'>
            <div class="credit-card-box">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="card_number">Card Number</label>
                            <div class="input-group">
                                <input
                                    type="tel"
                                    class="form-control"
                                    name="card_number"
                                    placeholder="Valid Card Number"
                                    autocomplete="cc-number"
                                    required autofocus
                                />
                                <span class="input-group-addon">
                                  <i class="fa fa-credit-card">
                                </i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                  <div class="col-xs-7 col-md-7">
                      <div class="form-group">
                          <label for="card_expiry"><span class="hidden-xs">Expiration Date</span><span class="visible-xs-inline">EXP</span> Date</label>
                          <input
                              type="tel"
                              class="form-control"
                              name="card_expiry"
                              placeholder="MM / YY"
                              autocomplete="cc-exp"
                              required
                          />
                      </div>
                  </div>
                  <div class="col-xs-5 col-md-5 pull-right">
                      <div class="form-group">
                        <label for="card_cvc">CVC</label>
                        <input
                            type="tel"
                            class="form-control"
                            name="card_cvc"
                            placeholder="CVC"
                            autocomplete="cc-csc"
                            required
                        />
                      </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
        <div class='row'>
          <div class="col-xs-12">
              <button class="subscribe btn btn-success btn-lg btn-block" type="submit">
                Pay
              </button>
          </div>
        </div>
        <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoltinSampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<%- @products.each_slice(4) do |slice| %>
  <div class='row'>
    <%- slice.each do |product| %>
      <div class='col-xs-12 col-sm-6 col-md-3'>
        <div class='well'>
          <% if product.files %>
            <% if file = @products.included.find('files', product.files.first.id) %>
              <%= image_tag file.href %>
            <% end %>
          <% end %>
          <br/>
          <%= link_to product.name, product_path(product.id) %>
          <br/><br/>
          <div class='row'>
            <div class='col-xs-12'>
              <%= link_to add_carts_path(product_id: product.id), method: :post, class: 'btn btn-primary' do %>
                <%= "Add To Cart (#{money(product.price.first)})" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= render 'shared/pagination', page: @page %>

app/views/products/show.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-4 col-md-offset-4'>
    <div class='well'>
      <% if @product.files %>
        <%- if file = @product.included.find('files', @product.files.first.id) %>
          <%= image_tag file.href %>
        <% end %>
      <% end %>
      <br/>
      <%= @product.name %>
      <br/><br/>
      <div class='row'>
        <%- @images.each do |image| %>
          <div class='col-xs-12 col-md-3'>
            <%= image_tag image.href %>
          </div>
        <% end %>
      </div>
      <div class='row'>
        <div class='col-xs-12'>
          <%= link_to add_carts_path(product_id: @product.id), class: 'btn btn-primary', method: :post do %>
            <%= "Add To Cart (#{money(@product.price.first)})" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My Moltin Shop</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Products', products_path %></li>
      </ul>
      <%= form_tag root_path, method: :get, class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag :query, @query, class: 'form-control', placeholder: 'Search...' %>
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Cart', carts_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_pagination.html.erb
<nav aria-label="Page navigation" class='text-center'>
  <ul class="pagination">
    <% unless page['current'] == 1 %>
      <li>
        <%= link_to root_path(page: 1) do %>
          <span aria-hidden="true">&laquo;</span>
        <% end %>
      </li>
      <li>
        <%= link_to page['current'] - 1, root_path(page: page['current'] - 1) %>
      </li>
    <% end %>

    <li class="active"><a href="#"><%= page['current'] %> <span class="sr-only">(current)</span></a></li>

    <% unless page['current'] == page['total'] %>
      <li><%= link_to page['current'] + 1, root_path(page: page['current'] + 1) %></li>
      <li>
        <%= link_to root_path(page: page['total']) do %>
          <span aria-hidden="true">&raquo;</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>